### ISSUE TITLE
JupyterLab & Codespaces compatibility issue

### ISSUE THREAD

**Issue by nakytoe** [Datahel/tabular-anonymizer#2]
Problem: 

README has the following in the part about Codespaces:

Tip: If you want to run jupyter-lab server in codespaces, use following command:

    jupyter-lab --ip 0.0.0.0 --config .devcontainer/jupyter-server-config.py --no-browser
Then add port-mapping to port 8888.

One can indeed launch jupyterlab. However, the port forwarding does not work - no code, notebooks or  terminal commands can be executed from the jupyterlab view. 

How to reproduce: 
Follow the readme instructions on the codespaces part at commit d7e7a97f4d71f07c022870fc4913882f99b3cc42

Suggestion: either fix the issue or remove this from README

**Comment by manujoha** [comment]
Jupyterlab server should indeed work out-of-box by following updated readme. Please verify that this actually works in your environment too.
