### ISSUE TITLE
Can't run DataFrameAnonymizer examples

### ISSUE THREAD

**Issue by PetjaS** [Datahel/tabular-anonymizer#5]
Python 3.10

Running: 

```
import pandas as pd
from tabular_anonymizer import DataFrameAnonymizer

# Setup dataframe
df = pd.read_csv("./adult.csv", sep=",")

# Define sensitive attributes
sensitive_columns = ['label']

# Anonymize dataframe with k=10
p = MondrianAnonymizer(sensitive_columns)
df_anonymized = p.anonymize_k_anonymity(df, k=10)
```

Returns:
`NameError: name 'MondrianAnonymizer' is not defined
`

After importing MondrianAnonymizer function manually, returns:
`TypeError: MondrianAnonymizer.__init__() missing 2 required positional arguments: 'feature_columns' and 'sensitive_columns'`

**Comment by manujoha** [comment]
Thanks for comment. There was a flaw in REAME.md. I fixed it to main branch. 

Example mentioned in readme assumes that you have tabular-anonymizer installed as dependency in your environment together with file adult.csv. Eg. 

```
pip install -e <anonymizer-parent-dir>/tabular-anonymizer
cp <anonymizer-parent-dir>/tabular-anonymizer/examples/adult.csv ./
```

Then just replace MondrianAnonymizer as DataFrameAnonymizer:

```
import pandas as pd
from tabular_anonymizer import DataFrameAnonymizer

# Setup dataframe
df = pd.read_csv("./adult.csv", sep=",")

# Define sensitive attributes
sensitive_columns = ['label']

# Anonymize dataframe with k=10
p = DataFrameAnonymizer(sensitive_columns)
df_anonymized = p.anonymize_k_anonymity(df, k=10)
```
